### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by swvanderlaan** [alexvpickering/rnama-client#1]
Hi,

I'm on macOS High Sierra (10.13.6) with Safari and I forgot my password. I followed the "Forgot my password"-link under "Sign In", however after filling in my registered email, nothing seem to happen when I hit the orange/yellow button with the `>`.

Do you have a solution?

Thanks!

Sander

**Comment by alexvpickering** [comment]
Hey Sander,

Will implement today after I put my daughter down for a nappy. Sorry about that.

**Comment by alexvpickering** [comment]
Should be good now. Let me know if anything else comes up.
