### ISSUE TITLE
GEO studies search box can't find studies

### ISSUE THREAD

**Issue by thiago22yow** [alexvpickering/rnama-client#30]
Hello, I'm trying to select a few GEO studies in the search box but they wouldn't show up in the results (GSE19080, GSE55851). Am I doing something wrong or are they not available?
Thanks!

**Comment by alexvpickering** [comment]
Unfortunately, those studies are not available. It all depends on whether [crossmeta](https://github.com/alexvpickering/crossmeta) can load the raw  data for a given study.

The platform for GSE19080 (non-commercial) is not very common on GEO, so I have not written code for crossmeta to load it. You are welcome to submit a PR on crossmeta to load this platform as long as it has generality to it (i.e. it will also load a substantial number of other GEO studies that crossmeta currently chokes on).

For GSE55851, the manufacturer (Agilent) produces many platforms with various data formats. crossmeta will load some Agilent platforms but not all. Again, I would welcome a PR to crossmeta that allows it to load the raw data for GSE55851 so long as it has generality.

**Comment by thiago22yow** [comment]
Oh that's too bad. Unfortunately I'm a complete neophyte, can't help with that
Thanks for your anwser!
